[package]
name = "gss-app"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
# Internal crates
alerting = { path = "../gss-core/alerting" }
file_ops = { path = "../gss-core/file_ops" }
files = { path = "../gss-core/files" }
stores = { path = "../gss-core/stores" }
types = { path = "../gss-core/types" }
properties = { path = "../gss-core/properties" }
constants = { path = "../gss-core/constants" }

# External crates
iced.workspace = true
iced.features = ["canvas", "tokio", "debug"]
iced_aw = { workspace = true, features = [ "full" ] } 
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true, features = ["json"] }
chrono.workspace = true
rfd.workspace = true