[package]
name = "stores"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]  
doctest = false 
test = false

[dependencies]
#Internal crates
types = { path = "../types" }
files = { path = "../files" }
properties = { path = "../properties" }
constants = { path = "../constants" }
errors = { path = "../errors" }

# External crates
tokio.workspace = true
reqwest = { workspace = true, features = ["json", "cookies"] }
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
regex.workspace = true
exitcode.workspace = true
rand.workspace = true
chrono.workspace = true
mockall.workspace = true
async-trait.workspace = true