pub static CHECK_MARK : &str = "✔";
pub static UP_ARROW : &str = "▲";
pub static DOWN_ARROW : &str = "▼";
pub static LEFT_ARROW : &str = "▶";
pub static LEFT_ARROW_LONG : &str = "←";
pub static RIGHT_ARROW_LONG: &str = "→";
pub static FLOPPY_DISK : &str = "💾";
pub static TRASH_BIN : &str = "🗑️";
pub static RETRY : &str = "🔁";