[package]
name = "gss-tests"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
# Internal crates
alerting = { path = "../gss-core/alerting" }
file_ops = { path = "../gss-core/file_ops" }
file_types = { path = "../gss-core/file_types" }
stores = { path = "../gss-core/stores" }
structs = { path = "../gss-core/structs" }
properties = { path = "../gss-core/properties" }
constants = { path = "../gss-core/constants" }

# External crates
reqwest = { workspace = true, features = ["json", "blocking"] }
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive", "cargo"] }
dotenv.workspace = true
dotenvy.workspace = true
serde_json.workspace = true
regex.workspace = true
rand.workspace = true