[package]
name = "alerting"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]  
doctest = false
test = false

[dependencies]
# Internal crates
structs = { path = "../structs" }
properties = { path = "../properties" }
constants = { path = "../constants" }

# External crates
lettre.workspace = true